[package]
name = "hypr-magic"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = "0.8"
glib = "0.19"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1"
